### ISSUE TITLE
What is the batch_size parameter used by the network? I do not see the batch_size parameter in the code

### ISSUE THREAD

**Issue by a139122679** [yueliu1999/DCRN#1]

**Comment by yueliu1999** [comment]
Thanks for your issue. For DBLP, ACM, CITE, and AMAP datasets, we input the whole graphs. Limited by the NVIDIA 3090 GPU memory, PUBMED and CORAFULL might be out of memory during training. Thus, we adopt the batch training version of DCRN. To be specific, the training batch size is set to 2000, more details about batch training please check the following link: https://drive.google.com/file/d/185GLObsQQL3Y-dQ2aIin5YrXuA-dgpnU/view

**Comment by a139122679** [comment]
Okay, thanks for your reply.
