### ISSUE TITLE
數據集

### ISSUE THREAD

**Issue by Lorraine-Kwok** [yueliu1999/DCRN#9]
您好！請問一下DCRN可以用在類似於OFFICE數據集等無監督圖想聚類任務嗎？如果要應用，怎麼生成符合要求的.npy文件呢？

**Comment by yueliu1999** [comment]
您好，感谢关注。这个npy是numpy包生成的numpy数组文件。你也可以直接把你的OFFICE文件读入代码来完成聚类任务。其中X是N * d的节点属性矩阵，y是N * 1的标签矩阵，A是N * N的邻接矩阵。N是节点的数量，d是特征的维度。

**Comment by Lorraine-Kwok** [comment]
好的好的，謝謝前輩，麻煩您了！
